install.packages("caret")
library(caret)
data(iris)
dataset<-iris
validation_index<-createDataPartition(dataset$Species,p=0.80,list=FALSE)
validation<-dataset[-validation_index,]
dataset<-dataset[-validation_index,]
sapply(dataset,class)
levels(dataset$Species)
percentage<-prop.table(table(dataset$species))*100
cbind(freq=table(dataset$Species),percentage=percentage)
summary(dataset)
x<-dataset[,1:4]
y<-dataset[,5]
par(mfrow=c(1,4))
for(i in 1:4){
  boxplot(x[,i],main=names(iris)[i])
}
plot(y)
featurePlot(x=x,y=y,plot="box")
scales<-list(x=list(relation="free"),y=list(relation="free"))
featurePlot(x=x,y=y,plot="density",scales=scales)
control<-trainControl(method = "cv",number=10)
metric<-"Accuracy"
set.seed(7)
fit.lda<-train
(Species~.,data=dataset,method="lda",metric=metric,trcontrol=control)
set.seed(7)
fit.svm<-train(Species~.,data=dataset,
               method="svmRadial",metric=metric,trcontrol=control)
set.seed(7)
fit.rf<-train
(Species~.,data=dataset,method="rf",metric=metric,trcontrol=control)
results<-resamples(list(lda=fit.lda,svm=fit.svm,rf=fit.rf))
summary(results)
dotplot(results)
print(fit.lda)
predictions<-predict(fit.lda,validation)
confusionMatrix(predictions,validation$Species)

